Vagrant.configure("2") do |config|
  # Define web01
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/focal64"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.2"

    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    web01.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install apache2 wget unzip -y
      systemctl start apache2
      systemclt enable apache2
      cd /tmp/
      wget https://www.tooplate.com/zip-templates/2135_mini_finance.zip
      unzip -o 2135_mini_finance.zip
      cp -r 2135_mini_finance/* /var/www/html/
      systemctl restart apache2
    SHELL
  end

  config.vm.define "db01" do |db01|
    db01.vm.box = "eurolinux-vagrant/centos-stream-9"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.3"

    db01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"  # Set a lower memory value if needed
    end

    # Provisioning to install MariaDB
    db01.vm.provision "shell", inline: <<-SHELL
      sudo yum install -y wget unzip mariadb-server -y
      sudo systemctl start mariadb
      sudo systemctl enable mariadb
      mysql -u root -e 'CREATE DATABASE wordpress;'
      mysql -u root -e 'CREATE USER wordpress@localhost IDENTIFIED BY "admin123";'
      mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost;'
      mysql -u root -e 'FLUSH PRIVILEGES;'
    SHELL
  end
end