Vagrant.configure("2") do |config|
  # Define web01
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/focal64"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.41"

    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"  # Set a lower memory value if needed
    end
  end

  # Define web02
  config.vm.define "web02" do |web02|
    web02.vm.box = "ubuntu/focal64"
    web02.vm.hostname = "web02"
    web02.vm.network "private_network", ip: "192.168.56.42"

    web02.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"  # Set a lower memory value if needed
    end
  end

  # Define web03
  config.vm.define "web03" do |web03|
    web03.vm.box = "ubuntu/focal64"
    web03.vm.hostname = "web03"
    web03.vm.network "private_network", ip: "192.168.56.45"

    web03.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"  # Set a lower memory value if needed
    end
  end

  # Define db01 with CentOS 7 and provisioning
  config.vm.define "db01" do |db01|
    db01.vm.box = "centos/7"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.43"

    db01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"  # Set a lower memory value if needed
    end

    # Provisioning to install MariaDB
    db01.vm.provision "shell", inline: <<-SHELL
      sudo yum install -y wget unzip mariadb-server -y
      sudo systemctl start mariadb
      sudo systemctl enable mariadb
    SHELL
  end
end
